name: 'Emoji Generator
description: 'Generates an emoji when someone opens a pull request'
author: 'George Lin - lingeorge88'
inputs:
  github-token:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'